Repository micronaut-projects/micronaut-liquibase, pull requests merged in 2020-09, with the labels that each got.

#79 [liquibase] Update common files for branch 1.3.x
  .github/workflows/release-notes.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build

#78 [liquibase] Update common files for branch master
  .github/workflows/release-notes.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build

#81 fix: onCreated should not return unwrapped datasource
  liquibase/src/main/java/io/micronaut/liquibase/LiquibaseMigrationRunner.java
  liquibase/src/test/groovy/io/micronaut/liquibase/ApplicationContextSpecification.groovy
  liquibase/src/test/groovy/io/micronaut/liquibase/ConfigurationFixture.groovy
  liquibase/src/test/groovy/io/micronaut/liquibase/LiquibaseMigrationRunnerSpec.groovy
Labels: type: bug

#88 ci: set github core branch to 2.0.x
  gradle.properties
Labels: relates-to: build

#90 ci: downgrade liquibase version to 3.8.0
  gradle.properties
Labels: relates-to: build, type: dependency-upgrade
