Repository micronaut-projects/micronaut-liquibase, pull requests merged in 2022-11, with the labels that each got.

#302 throw ConfigurationException if `datasources.[name].schema-generate` enabled for liquibase enabled configuration with same `name`
  .github/workflows/graalvm.yml
  liquibase/src/main/java/io/micronaut/liquibase/LiquibaseConfigurationProperties.java
  liquibase/src/test/groovy/io/micronaut/liquibase/LiquibaseConfigurationPropertiesEnabledSpec.groovy
Labels: type: improvement

#297 ci: java temurin distro and CLA provenance
  .github/workflows/central-sync.yml
  .github/workflows/gradle.yml
  .github/workflows/publish-snapshot.yml
  .github/workflows/release.yml
  .github/workflows/sonarqube.yml
Labels: relates-to: build

#306 graal: simplify the resource-config.json of adding dbchangelog xsds
  liquibase/src/main/resources/META-INF/native-image/io.micronaut.liquibase/micronaut-liquibase/resource-config.json
Labels: relates-to: graal

#307 build: gradle 7.6
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: relates-to: build
