Repository micronaut-projects/micronaut-liquibase, pull requests merged in 2023-04, with the labels that each got.

#353 add graal tests
  .github/workflows/graalvm.yml
  buildSrc/build.gradle
  buildSrc/settings.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.liquibase-base.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.liquibase-native-tests.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.liquibase-tests.gradle
  buildSrc/src/main/groovy/io.micronaut.build.internal.liquibase.test-suite-graal.gradle
  gradle/libs.versions.toml
  settings.gradle
  test-suite-graal-h2/build.gradle
  test-suite-graal-h2/src/main/java/micronaut/example/JdbcUserRepository.java
  test-suite-graal-h2/src/main/resources/application.yml
  test-suite-graal-h2/src/test/java/micronaut/example/UserControllerTest.java
  test-suite-graal-mariadb/build.gradle
  test-suite-graal-mariadb/src/main/java/micronaut/example/JdbcUserRepository.java
  test-suite-graal-mariadb/src/main/resources/application.yml
  test-suite-graal-mariadb/src/test/java/micronaut/example/UserControllerTest.java
  test-suite-graal-postgres/build.gradle
  test-suite-graal-postgres/src/main/java/micronaut/example/JdbcUserRepository.java
  test-suite-graal-postgres/src/main/resources/application.yml
  test-suite-graal-postgres/src/test/java/micronaut/example/UserControllerTest.java
  test-suite-graal/build.gradle
  test-suite-graal/src/main/java/micronaut/example/Application.java
  test-suite-graal/src/main/java/micronaut/example/User.java
  test-suite-graal/src/main/java/micronaut/example/UserController.java
  test-suite-graal/src/main/java/micronaut/example/UserRepository.java
  test-suite-graal/src/main/resources/db/changelog/01-create-users-table.xml
  test-suite-graal/src/main/resources/db/changelog/02-insert-users-data.xml
  test-suite-graal/src/main/resources/db/liquibase-changelog.xml
  test-suite-graal/src/main/resources/logback.xml
Labels: relates-to: graal

#355 bug: fixes graal error MdcManagerFactory.<init>
  liquibase/src/main/resources/META-INF/native-image/io.micronaut.liquibase/micronaut-liquibase/reflect-config.json
Labels: relates-to: graal, type: bug

#349 [liquibase] Update common files for branch master
  .github/workflows/gradle.yml
  gradle/wrapper/gradle-wrapper.properties
Labels: relates-to: build

#361 M2
  buildSrc/src/main/groovy/io.micronaut.build.internal.liquibase.test-suite-graal.gradle
  gradle/libs.versions.toml
  liquibase/src/main/resources/META-INF/native-image/io.micronaut.liquibase/micronaut-liquibase/reflect-config.json
  settings.gradle
  test-suite-graal-h2/build.gradle
  test-suite-graal-mariadb/build.gradle
  test-suite-graal-postgres/build.gradle
  test-suite-graal/build.gradle
Labels: type: dependency-upgrade
